### ISSUE TITLE
Some question about the paper.

### ISSUE THREAD

**Issue by guotong1988** [IBM/SQL-to-Text#1]
we get text from SQL, then how can we use text to query the database?

Thank you very much.

@stevemart

**Comment by teddylfwu** [comment]
Could you elaborate more on your problem?

Our codes will be released in one month. You will see some examples in our
codes.

Yours sincerely,

Lingfei (Teddy) Wu
Research Staff Member, AI Foundations Labs - Reasoning
IBM Research AI
IBM T. J. Watson Research Center, Yorktown Heights, NY 10598
Phone: +1 757-634-5455
Email: lwu@email.wm.edu, wuli@us.ibm.com

**Comment by guotong1988** [comment]
Thank for your reply.
In WikiSQL dataset, we transform text to SQL and then query the database.
In the end we get the answer corresponding to the text.
I cannot understand how graph2seq get the answer for a SQL.

**Comment by teddylfwu** [comment]
Using grpah2seq model for converting SQL to text has attracted a surge of
interests recently.

Please see the following two papers for getting a better understanding of
this task.

https://arxiv.org/abs/1809.05255

https://arxiv.org/abs/1805.02473


Yours sincerely,

Lingfei (Teddy) Wu
Research Staff Member, AI Foundations Labs - Reasoning
IBM Research AI
IBM T. J. Watson Research Center, Yorktown Heights, NY 10598
Phone: +1 757-634-5455
Email: lwu@email.wm.edu, wuli@us.ibm.com

**Comment by guotong1988** [comment]
Oh, I know, the task is transforming SQL to text, without query the database.
